In [27]:
from pathlib import Path
import logging
import fastf1 as ff1
import pandas as p

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
cache_path = Path("ff1_cache")
cache_path.mkdir(parents=True, exist_ok=True)
ff1.Cache.enable_cache(cache_path)

session = ff1.get_session(2024, 'Monza', 'R')
session.load()

goat = session.laps.pick_drivers('LEC').pick_fastest()
data = goat.get_car_data()

df = p.DataFrame(data)
df.head(10)

core           INFO 	Loading data for Italian Grand Prix - Race [v3.6.1]
2025-11-17 09:14:21,102 - INFO - Loading data for Italian Grand Prix - Race [v3.6.1]
req            INFO 	Using cached data for session_info
2025-11-17 09:14:21,104 - INFO - Using cached data for session_info
req            INFO 	Using cached data for driver_info
2025-11-17 09:14:21,104 - INFO - Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
2025-11-17 09:14:21,122 - INFO - Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
2025-11-17 09:14:21,123 - INFO - Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
2025-11-17 09:14:21,124 - INFO - Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
2025-11-17 09:14:21,133 - INFO - Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
2025-11-17 09:14:21,137 - INFO - Using cached data for timing_app_data
core           INFO 	Processing timing data...
2025-11-17 09:14:21,137 - INFO - Processing timing data...
req            INFO 	Using cached data for car_data
2025-11-17 09:14:21,525 - INFO - Using cached data for car_data
req            INFO 	Using cached data for position_data
2025-11-17 09:14:21,609 - INFO - Using cached data for position_data
req            INFO 	Using cached data for weather_data
2025-11-17 09:14:22,494 - INFO - Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
2025-11-17 09:14:22,496 - INFO - Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']
2025-11-17 09:14:22,522 - INFO - Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2024-09-01 13:49:00.270,11305.0,317.0,8,100.0,False,14,car,0 days 00:00:00.106000,0 days 01:41:16.351000
1,2024-09-01 13:49:00.630,11433.0,320.0,8,99.0,False,12,car,0 days 00:00:00.466000,0 days 01:41:16.711000
2,2024-09-01 13:49:00.830,11465.0,322.0,8,99.0,False,12,car,0 days 00:00:00.666000,0 days 01:41:16.911000
3,2024-09-01 13:49:00.990,11465.0,324.0,8,99.0,False,12,car,0 days 00:00:00.826000,0 days 01:41:17.071000
4,2024-09-01 13:49:01.310,11595.0,326.0,8,99.0,False,12,car,0 days 00:00:01.146000,0 days 01:41:17.391000
5,2024-09-01 13:49:01.470,11666.0,327.0,8,99.0,False,12,car,0 days 00:00:01.306000,0 days 01:41:17.551000
6,2024-09-01 13:49:01.710,11723.0,329.0,8,100.0,False,12,car,0 days 00:00:01.546000,0 days 01:41:17.791000
7,2024-09-01 13:49:01.910,11749.0,331.0,8,99.0,False,12,car,0 days 00:00:01.746000,0 days 01:41:17.991000
8,2024-09-01 13:49:02.310,11851.0,333.0,8,99.0,False,12,car,0 days 00:00:02.146000,0 days 01:41:18.391000
9,2024-09-01 13:49:02.470,11878.0,335.0,8,99.0,False,12,car,0 days 00:00:02.306000,0 days 01:41:18.551000

In [30]:
brakedf = df.loc[df['Brake'] == True].copy()

brakedf["speed_next"] = brakedf["Speed"].shift(-5)

brakedf["speed_diff"] = (brakedf["Speed"] - brakedf["speed_next"]) / brakedf["Speed"]

hardBrake = brakedf[brakedf["speed_diff"] > 0.4]

hardBrake.head(10)

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime,speed_next,speed_diff
33,2024-09-01 13:49:08.430,11472.0,329.0,8,61.0,True,0,car,0 days 00:00:08.266000,0 days 01:41:24.511000,150.0,0.544073
34,2024-09-01 13:49:08.870,10632.0,263.0,7,2.0,True,0,car,0 days 00:00:08.706000,0 days 01:41:24.951000,122.0,0.536122
35,2024-09-01 13:49:09.190,10729.0,226.0,6,2.0,True,0,car,0 days 00:00:09.026000,0 days 01:41:25.271000,111.0,0.508850
36,2024-09-01 13:49:09.390,10690.0,205.0,6,1.0,True,0,car,0 days 00:00:09.226000,0 days 01:41:25.471000,103.0,0.497561
37,2024-09-01 13:49:09.590,11376.0,205.0,6,2.0,True,0,car,0 days 00:00:09.426000,0 days 01:41:25.671000,92.0,0.551220
38,2024-09-01 13:49:09.949,11397.0,150.0,4,3.0,True,0,car,0 days 00:00:09.785000,0 days 01:41:26.030000,86.0,0.426667
110,2024-09-01 13:49:28.510,11027.0,311.0,8,99.0,True,0,car,0 days 00:00:28.346000,0 days 01:41:44.591000,163.0,0.475884
111,2024-09-01 13:49:28.750,10314.0,281.0,8,3.0,True,0,car,0 days 00:00:28.586000,0 days 01:41:44.831000,131.0,0.533808
112,2024-09-01 13:49:28.910,10122.0,267.0,8,1.0,True,0,car,0 days 00:00:28.746000,0 days 01:41:44.991000,123.0,0.539326
113,2024-09-01 13:49:29.230,9969.0,226.0,8,3.0,True,0,car,0 days 00:00:29.066000,0 days 01:41:45.311000,117.0,0.482301

In [26]:
hardBrake.size

132